# Generated by Django 4.2.16 on 2026-01-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_add_reality_form_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_key', models.CharField(choices=[('feed', 'Feed Principal'), ('profile', 'Perfil'), ('users', 'Usuarios'), ('notifications', 'Notificaciones'), ('clips', 'Clips'), ('reels', 'Reels'), ('live', 'En Vivo'), ('communities', 'Comunidades'), ('classifieds', 'Clasificados'), ('donations', 'Donaciones'), ('habil-news', 'Hábil News'), ('messages', 'Mensajes'), ('settings', 'Configuración')], max_length=50, unique=True, verbose_name='Ruta')),
                ('label', models.CharField(max_length=100, verbose_name='Etiqueta del menú')),
                ('path', models.CharField(help_text='Ejemplo: /feed, /communities', max_length=200, verbose_name='Ruta URL')),
                ('icon', models.CharField(choices=[('Home', 'Inicio'), ('User', 'Usuario'), ('Users', 'Usuarios'), ('Bell', 'Campana'), ('Video', 'Video'), ('Film', 'Película'), ('Radio', 'Radio/En Vivo'), ('Users', 'Comunidad'), ('ShoppingBag', 'Bolsa de compras'), ('Heart', 'Corazón'), ('Newspaper', 'Periódico'), ('MessageSquare', 'Mensajes'), ('Settings', 'Configuración')], max_length=50, verbose_name='Icono')),
                ('is_enabled', models.BooleanField(default=True, help_text='Si está deshabilitado, la ruta no aparecerá en el menú y retornará 404', verbose_name='Habilitado')),
                ('order', models.IntegerField(default=0, help_text='Orden de aparición en el menú (menor número = más arriba)', verbose_name='Orden')),
                ('badge_count', models.IntegerField(default=0, help_text='Número que aparece en el badge (0 = no mostrar)', verbose_name='Contador de badge')),
                ('requires_auth', models.BooleanField(default=True, help_text='Si está marcado, solo usuarios autenticados pueden acceder', verbose_name='Requiere autenticación')),
                ('description', models.TextField(blank=True, help_text='Descripción interna de la funcionalidad', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Ruta del Menú',
                'verbose_name_plural': 'Configuración del Menú',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Configuración del Sitio', 'verbose_name_plural': 'Configuración del Sitio'},
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='reality_form_enabled',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='show_register_habilidosos_button',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_url',
            field=models.URLField(blank=True, verbose_name='URL del logo'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_message',
            field=models.TextField(blank=True, verbose_name='Mensaje de mantenimiento'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='Modo mantenimiento'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#00ff88', max_length=7, verbose_name='Color primario'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(blank=True, verbose_name='Descripción del sitio'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='SOS Habilidoso', max_length=100, verbose_name='Nombre del sitio'),
        ),
        migrations.AlterModelTable(
            name='sitesettings',
            table=None,
        ),
    ]
