# Generated by Django 4.2.16 on 2026-01-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_menuroute_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='reality_form_enabled',
            field=models.BooleanField(default=True, help_text='Activa o desactiva el acceso al formulario de registro del reality', verbose_name='Formulario Reality habilitado'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_register_habilidosos_button',
            field=models.BooleanField(default=True, help_text='Activa o desactiva la visibilidad del botón de registro de habilidosos en toda la aplicación', verbose_name="Mostrar botón 'Registrarte'"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
    ]
