# Generated by Django 5.2.11 on 2026-02-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_sitesettings_reality_form_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sidebar_show_classifieds',
            field=models.BooleanField(default=True, help_text='Ocultar/Mostrar la sección de Clasificados en el sidebar', verbose_name='Mostrar Clasificados'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sidebar_show_clips',
            field=models.BooleanField(default=True, help_text='Ocultar/Mostrar la sección de Clips en el sidebar', verbose_name='Mostrar Clips'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sidebar_show_communities',
            field=models.BooleanField(default=True, help_text='Ocultar/Mostrar la sección de Comunidades en el sidebar', verbose_name='Mostrar Comunidades'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sidebar_show_donations',
            field=models.BooleanField(default=True, help_text='Ocultar/Mostrar la sección de Donaciones en el sidebar', verbose_name='Mostrar Donaciones'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sidebar_show_feed',
            field=models.BooleanField(default=True, help_text='Ocultar/Mostrar la sección de Feed en el sidebar para todos los usuarios', verbose_name='Mostrar Feed/Inicio'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sidebar_show_live',
            field=models.BooleanField(default=True, help_text='Ocultar/Mostrar la sección de Transmisiones en Vivo en el sidebar', verbose_name='Mostrar En Vivo'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sidebar_show_messages',
            field=models.BooleanField(default=True, help_text='Ocultar/Mostrar la sección de Mensajes en el sidebar', verbose_name='Mostrar Mensajes'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sidebar_show_news',
            field=models.BooleanField(default=True, help_text='Ocultar/Mostrar la sección de Noticias en el sidebar', verbose_name='Mostrar Hábil News'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sidebar_show_notifications',
            field=models.BooleanField(default=True, help_text='Ocultar/Mostrar la sección de Notificaciones en el sidebar', verbose_name='Mostrar Notificaciones'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sidebar_show_profile',
            field=models.BooleanField(default=True, help_text='Ocultar/Mostrar la sección de Perfil en el sidebar', verbose_name='Mostrar Perfil'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sidebar_show_reels',
            field=models.BooleanField(default=True, help_text='Ocultar/Mostrar la sección de Reels en el sidebar', verbose_name='Mostrar Reels'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sidebar_show_search',
            field=models.BooleanField(default=True, help_text='Ocultar/Mostrar la sección de Búsqueda de usuarios en el sidebar', verbose_name='Mostrar Buscar'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sidebar_show_settings',
            field=models.BooleanField(default=True, help_text='Ocultar/Mostrar la sección de Configuración en el sidebar', verbose_name='Mostrar Configuración'),
        ),
    ]
