# Generated by Django 4.2.16 on 2025-12-13 05:51

import apps.media_storage.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.media_storage.models.upload_to_media, verbose_name='Archivo')),
                ('file_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Documento')], max_length=10, verbose_name='Tipo de archivo')),
                ('original_name', models.CharField(max_length=255, verbose_name='Nombre original')),
                ('file_size', models.PositiveIntegerField(verbose_name='Tamaño del archivo (bytes)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='Tipo MIME')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ancho')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Alto')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duración')),
                ('is_public', models.BooleanField(default=True, verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Archivo Multimedia',
                'verbose_name_plural': 'Archivos Multimedia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAlbum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del álbum')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_public', models.BooleanField(default=True, verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('files', models.ManyToManyField(related_name='albums', to='media_storage.mediafile', verbose_name='Archivos')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_albums', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Álbum Multimedia',
                'verbose_name_plural': 'Álbumes Multimedia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='media_stora_uploade_37f33e_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['file_type', '-created_at'], name='media_stora_file_ty_a1d710_idx'),
        ),
    ]
