# Generated by Django 4.2.26 on 2025-11-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community_posts/images/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='podcast',
            field=models.FileField(blank=True, null=True, upload_to='community_posts/podcasts/', verbose_name='Podcast'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='community_posts/videos/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='communitymembership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='communitysociallink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
