# Generated by Django 4.2.7 on 2025-12-03 12:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_communitypost_image_communitypost_podcast_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icono (emoji o clase)')),
                ('color', models.CharField(default='#00ff88', max_length=7, verbose_name='Color (hex)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Imagen')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='community',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcommunities', to='communities.community', verbose_name='Comunidad padre'),
        ),
        migrations.AlterField(
            model_name='community',
            name='category',
            field=models.CharField(blank=True, choices=[('deportes', 'Deportes'), ('musica', 'Música'), ('arte', 'Arte'), ('gaming', 'Gaming'), ('tecnologia', 'Tecnología'), ('lifestyle', 'Lifestyle'), ('educacion', 'Educación'), ('negocios', 'Negocios'), ('salud', 'Salud'), ('viajes', 'Viajes')], max_length=20, verbose_name='Categoría (legacy)'),
        ),
        migrations.AddField(
            model_name='community',
            name='category_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='communities.communitycategory', verbose_name='Categoría'),
        ),
    ]
