# Generated by Django 4.2.16 on 2025-12-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_add_categories_subcommunities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Contenido'),
        ),
    ]
