# Generated by Django 4.2.26 on 2025-11-14 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('like', 'Me gusta'), ('celebration', 'Celebración'), ('golazo', 'Golazo'), ('comment', 'Comentario'), ('reply', 'Respuesta'), ('share', 'Compartido'), ('follow', 'Nuevo seguidor'), ('friend_request', 'Solicitud de amistad'), ('friend_accept', 'Amistad aceptada'), ('mention', 'Mención')], max_length=20, verbose_name='Tipo de notificación')),
                ('post_id', models.UUIDField(blank=True, null=True, verbose_name='ID del post')),
                ('comment_id', models.UUIDField(blank=True, null=True, verbose_name='ID del comentario')),
                ('message', models.TextField(max_length=500, verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_2d3764_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['sender', '-created_at'], name='notificatio_sender__6aaec3_idx')],
            },
        ),
    ]
