# Generated by Django 4.2.26 on 2025-11-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='friend_request_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='ID de solicitud de amistad'),
        ),
    ]
