# Generated by Django 4.2.16 on 2026-01-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_friend_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='story_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='ID de la historia'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Me gusta'), ('celebration', 'Celebración'), ('golazo', 'Golazo'), ('comment', 'Comentario'), ('reply', 'Respuesta'), ('share', 'Compartido'), ('follow', 'Nuevo seguidor'), ('friend_request', 'Solicitud de amistad'), ('friend_accept', 'Amistad aceptada'), ('mention', 'Mención'), ('story_reaction', 'Reacción a historia'), ('story_reply', 'Respuesta a historia')], max_length=20, verbose_name='Tipo de notificación'),
        ),
    ]
