# Generated by Django 5.2.6 on 2025-10-09 14:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Miembro'), ('admin', 'Administrador'), ('owner', 'Propietario')], default='member', max_length=10, verbose_name='Rol')),
                ('other_user_nickname', models.CharField(blank=True, max_length=50, verbose_name='Apodo del otro usuario')),
                ('chat_background', models.CharField(blank=True, max_length=20, verbose_name='Fondo del chat')),
                ('chat_color', models.CharField(blank=True, max_length=30, verbose_name='Color de mis mensajes')),
                ('other_message_color', models.CharField(blank=True, max_length=30, verbose_name='Color de otros mensajes')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Notificaciones habilitadas')),
                ('sound_enabled', models.BooleanField(default=True, verbose_name='Sonido habilitado')),
                ('is_muted', models.BooleanField(default=False, verbose_name='Silenciado')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Bloqueado')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('last_read_at', models.DateTimeField(auto_now_add=True, verbose_name='Última lectura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Participante de Chat',
                'verbose_name_plural': 'Participantes de Chat',
                'db_table': 'chat_participants',
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del chat')),
                ('chat_type', models.CharField(choices=[('private', 'Chat Privado'), ('group', 'Chat Grupal'), ('community', 'Chat de Comunidad')], default='private', max_length=15, verbose_name='Tipo de chat')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Descripción')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='chat_avatars/', verbose_name='Avatar del chat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Última actividad')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_chats', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('participants', models.ManyToManyField(related_name='chat_rooms', through='messaging.ChatParticipant', to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
            ],
            options={
                'verbose_name': 'Sala de Chat',
                'verbose_name_plural': 'Salas de Chat',
                'db_table': 'chat_rooms',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.chatroom', verbose_name='Sala de chat'),
        ),
        migrations.CreateModel(
            name='ChatInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('expired', 'Expirada')], default='pending', max_length=10, verbose_name='Estado')),
                ('message', models.TextField(blank=True, max_length=200, verbose_name='Mensaje de invitación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de invitación')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('expires_at', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invitado')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invitador')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='messaging.chatroom', verbose_name='Sala de chat')),
            ],
            options={
                'verbose_name': 'Invitación a Chat',
                'verbose_name_plural': 'Invitaciones a Chat',
                'db_table': 'chat_invitations',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=2000, verbose_name='Contenido')),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'Archivo'), ('emoji', 'Emoji'), ('system', 'Sistema')], default='text', max_length=10, verbose_name='Tipo de mensaje')),
                ('image', models.ImageField(blank=True, null=True, upload_to='messages/images/', verbose_name='Imagen')),
                ('video', models.FileField(blank=True, null=True, upload_to='messages/videos/', verbose_name='Video')),
                ('audio', models.FileField(blank=True, null=True, upload_to='messages/audio/', verbose_name='Audio')),
                ('file_url', models.URLField(blank=True, verbose_name='URL del archivo')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre del archivo')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño del archivo')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Editado')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.chatroom', verbose_name='Sala de chat')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='messaging.message', verbose_name='Respuesta a')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('laugh', '😂'), ('wow', '😮'), ('sad', '😢'), ('angry', '😠'), ('fire', '🔥'), ('golazo', '⚽')], max_length=10, verbose_name='Tipo de reacción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reacción')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messaging.message', verbose_name='Mensaje')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reacción a Mensaje',
                'verbose_name_plural': 'Reacciones a Mensajes',
                'db_table': 'message_reactions',
            },
        ),
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de lectura')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='messaging.message', verbose_name='Mensaje')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Mensaje Leído',
                'verbose_name_plural': 'Mensajes Leídos',
                'db_table': 'message_reads',
            },
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['chat_type', '-last_activity'], name='chat_rooms_chat_ty_cd4e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['created_by', '-created_at'], name='chat_rooms_created_b6023e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['user', '-joined_at'], name='chat_partic_user_id_902601_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['chat_room', 'user'], name='chat_partic_chat_ro_329d69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatparticipant',
            unique_together={('chat_room', 'user')},
        ),
        migrations.AddIndex(
            model_name='chatinvitation',
            index=models.Index(fields=['invitee', 'status', '-created_at'], name='chat_invita_invitee_cf6a66_idx'),
        ),
        migrations.AddIndex(
            model_name='chatinvitation',
            index=models.Index(fields=['chat_room', 'status'], name='chat_invita_chat_ro_306842_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatinvitation',
            unique_together={('chat_room', 'invitee')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat_room', 'created_at'], name='messages_chat_ro_6c0442_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='messages_sender__7375e3_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat_room', 'is_deleted', 'created_at'], name='messages_chat_ro_134f80_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['message', 'reaction_type'], name='message_rea_message_57565e_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['user', '-created_at'], name='message_rea_user_id_97e8d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together={('message', 'user', 'reaction_type')},
        ),
        migrations.AddIndex(
            model_name='messageread',
            index=models.Index(fields=['user', '-read_at'], name='message_rea_user_id_59f535_idx'),
        ),
        migrations.AddIndex(
            model_name='messageread',
            index=models.Index(fields=['message', 'user'], name='message_rea_message_19da3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messageread',
            unique_together={('message', 'user')},
        ),
    ]
