# Generated by Django 4.2.16 on 2026-01-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='story_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='ID de la historia'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'Archivo'), ('emoji', 'Emoji'), ('system', 'Sistema'), ('story_reply', 'Respuesta a Historia')], default='text', max_length=15, verbose_name='Tipo de mensaje'),
        ),
    ]
