# Generated by Django 4.2.16 on 2025-12-20 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Usuario de empresa')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Eslogan')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Descripción')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='enterprises/logos/', verbose_name='Logo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='enterprises/covers/', verbose_name='Imagen de portada')),
                ('category', models.CharField(choices=[('deportes', 'Deportes'), ('fitness', 'Fitness'), ('nutricion', 'Nutrición'), ('tecnologia', 'Tecnología'), ('salud', 'Salud'), ('educacion', 'Educación'), ('entretenimiento', 'Entretenimiento'), ('moda', 'Moda'), ('alimentos', 'Alimentos'), ('servicios', 'Servicios'), ('otro', 'Otro')], default='otro', max_length=50, verbose_name='Categoría')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Industria')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de fundación')),
                ('employees_count', models.CharField(blank=True, max_length=50, verbose_name='Número de empleados')),
                ('social_links', models.JSONField(blank=True, default=list, verbose_name='Redes sociales')),
                ('followers_count', models.PositiveIntegerField(default=0, verbose_name='Seguidores')),
                ('posts_count', models.PositiveIntegerField(default=0, verbose_name='Publicaciones')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificada')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_enterprises', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'enterprises',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseFollow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de seguimiento')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='enterprises.enterprise', verbose_name='Empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_enterprises', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Seguimiento de Empresa',
                'verbose_name_plural': 'Seguimientos de Empresas',
                'db_table': 'enterprise_follows',
                'unique_together': {('user', 'enterprise')},
            },
        ),
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['owner'], name='enterprises_owner_i_0d65ef_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['username'], name='enterprises_usernam_d73cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['category'], name='enterprises_categor_77db61_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['is_active', '-created_at'], name='enterprises_is_acti_d929f2_idx'),
        ),
    ]
