# Generated by Django 4.2.16 on 2025-12-13 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('icono', models.CharField(blank=True, max_length=50, verbose_name='Icono (nombre del componente)')),
                ('color', models.CharField(default='#00ff88', max_length=20, verbose_name='Color hexadecimal')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='learning/secciones/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'db_table': 'learning_secciones',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción corta')),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='basico', max_length=20, verbose_name='Nivel')),
                ('duracion_minutos', models.PositiveIntegerField(default=30, verbose_name='Duración (minutos)')),
                ('imagen_url', models.URLField(blank=True, verbose_name='URL de imagen')),
                ('video_url', models.URLField(blank=True, verbose_name='URL de video')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='learning.seccion', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'db_table': 'learning_temas',
                'ordering': ['seccion', 'orden', 'titulo'],
                'unique_together': {('seccion', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='TemaPuntoClave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=500, verbose_name='Punto clave')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_clave', to='learning.tema', verbose_name='Tema')),
            ],
            options={
                'verbose_name': 'Punto Clave',
                'verbose_name_plural': 'Puntos Clave',
                'db_table': 'learning_tema_puntos_clave',
                'ordering': ['tema', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='TemaContenido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subtitulo', models.CharField(max_length=200, verbose_name='Subtítulo')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='learning.tema', verbose_name='Tema')),
            ],
            options={
                'verbose_name': 'Contenido de Tema',
                'verbose_name_plural': 'Contenidos de Temas',
                'db_table': 'learning_tema_contenido',
                'ordering': ['tema', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('icono', models.CharField(max_length=50, verbose_name='Icono/Emoji')),
                ('color', models.CharField(default='#FFD700', max_length=20, verbose_name='Color')),
                ('puntos', models.PositiveIntegerField(default=10, verbose_name='Puntos')),
                ('temas_requeridos', models.PositiveIntegerField(default=0, verbose_name='Temas requeridos (cantidad mínima)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seccion_requerida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logros', to='learning.seccion', verbose_name='Sección requerida (completar toda)')),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'db_table': 'learning_logros',
                'ordering': ['puntos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioLogro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_obtenido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha obtenido')),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='learning.logro', verbose_name='Logro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros_obtenidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Logro de Usuario',
                'verbose_name_plural': 'Logros de Usuarios',
                'db_table': 'learning_usuario_logros',
                'unique_together': {('usuario', 'logro')},
            },
        ),
        migrations.CreateModel(
            name='ProgresoUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('no_iniciado', 'No Iniciado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado')], default='no_iniciado', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('tiempo_dedicado_minutos', models.PositiveIntegerField(default=0, verbose_name='Tiempo dedicado (min)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='learning.tema', verbose_name='Tema')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_learning', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Progreso de Usuario',
                'verbose_name_plural': 'Progresos de Usuarios',
                'db_table': 'learning_progreso_usuario',
                'unique_together': {('usuario', 'tema')},
            },
        ),
    ]
