# Generated by Django 4.2.16 on 2025-12-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='learning/temas/', verbose_name='Imagen de portada'),
        ),
        migrations.AddField(
            model_name='tema',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='learning/videos/', verbose_name='Video del tema'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='imagen_url',
            field=models.URLField(blank=True, verbose_name='URL de imagen externa'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='URL de video (YouTube, Vimeo)'),
        ),
    ]
