# Generated by Django 4.2.26 on 2025-11-14 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Balance Disponible')),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Balance Pendiente')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Ganado')),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Retirado')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Cuenta')),
                ('account_type', models.CharField(blank=True, max_length=20, verbose_name='Tipo de Cuenta')),
                ('account_holder_name', models.CharField(blank=True, max_length=200, verbose_name='Titular de la Cuenta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Billetera',
                'verbose_name_plural': 'Billeteras',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('subscription', 'Suscripción'), ('ad_revenue', 'Ingresos por Publicidad'), ('community_membership', 'Membresía de Comunidad'), ('tip', 'Propina/Donación'), ('course_purchase', 'Compra de Curso'), ('classified_ad', 'Anuncio Clasificado'), ('withdrawal', 'Retiro'), ('refund', 'Reembolso'), ('commission', 'Comisión')], max_length=30, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('currency', models.CharField(default='COP', max_length=3, verbose_name='Moneda')),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Comisión Plataforma')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Neto')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('failed', 'Fallida'), ('cancelled', 'Cancelada'), ('refunded', 'Reembolsada')], default='pending', max_length=20, verbose_name='Estado')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('reference_id', models.CharField(blank=True, max_length=200, verbose_name='ID de Referencia')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Método de Pago')),
                ('payment_gateway', models.CharField(blank=True, max_length=50, verbose_name='Pasarela de Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('free', 'Gratis'), ('pro', 'Pro'), ('creator', 'Creador'), ('business', 'Empresarial')], max_length=20, verbose_name='Tipo de Plan')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('currency', models.CharField(default='COP', max_length=3, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('cancelled', 'Cancelada'), ('expired', 'Expirada'), ('suspended', 'Suspendida')], default='active', max_length=20, verbose_name='Estado')),
                ('is_recurring', models.BooleanField(default=True, verbose_name='Renovación Automática')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de Fin')),
                ('next_billing_date', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Facturación')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cancelación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformRevenue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50, verbose_name='Fuente')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.transaction', verbose_name='Transacción Relacionada')),
            ],
            options={
                'verbose_name': 'Ingreso de Plataforma',
                'verbose_name_plural': 'Ingresos de Plataforma',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-created_at'], name='finance_tra_created_945fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='finance_tra_user_id_9a80f9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='finance_tra_status_0941b9_idx'),
        ),
    ]
