# Generated by Django 4.2.16 on 2026-01-19 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reelcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_reel_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
