# Generated by Django 4.2.16 on 2025-12-17 19:30

import apps.stories.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media', models.FileField(upload_to='stories/%Y/%m/%d/', verbose_name='Archivo multimedia')),
                ('media_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video')], default='image', max_length=10, verbose_name='Tipo de medio')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='stories/thumbnails/', verbose_name='Miniatura')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Visualizaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('expires_at', models.DateTimeField(default=apps.stories.models.get_expiry_time, verbose_name='Fecha de expiración')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historia',
                'verbose_name_plural': 'Historias',
                'db_table': 'stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de visualización')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='stories.story', verbose_name='Historia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Visualización de Historia',
                'verbose_name_plural': 'Visualizaciones de Historias',
                'db_table': 'story_views',
                'indexes': [models.Index(fields=['story', '-viewed_at'], name='story_views_story_i_ced952_idx'), models.Index(fields=['user', '-viewed_at'], name='story_views_user_id_028f51_idx')],
                'unique_together': {('user', 'story')},
            },
        ),
        migrations.CreateModel(
            name='StoryReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=500, verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='stories.story', verbose_name='Historia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_replies', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Respuesta de Historia',
                'verbose_name_plural': 'Respuestas de Historias',
                'db_table': 'story_replies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['story', '-created_at'], name='story_repli_story_i_46664c_idx'), models.Index(fields=['user', '-created_at'], name='story_repli_user_id_4ddf9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoryReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(choices=[('like', '❤️ Me gusta'), ('fire', '🔥 Fuego'), ('celebrate', '🎉 Celebración'), ('thumbsup', '👍 Pulgar arriba')], max_length=15, verbose_name='Tipo de reacción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reacción')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='stories.story', verbose_name='Historia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reacción de Historia',
                'verbose_name_plural': 'Reacciones de Historias',
                'db_table': 'story_reactions',
                'indexes': [models.Index(fields=['story', 'reaction_type'], name='story_react_story_i_ea66a3_idx'), models.Index(fields=['user', '-created_at'], name='story_react_user_id_15f3bc_idx')],
                'unique_together': {('user', 'story')},
            },
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['user', '-created_at'], name='stories_user_id_b336dc_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['expires_at'], name='stories_expires_a4b2b7_idx'),
        ),
    ]
