# Generated by Django 5.2.6 on 2025-10-09 14:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=2000, verbose_name='Contenido')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='Imágenes')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Miniatura')),
                ('podcast_url', models.URLField(blank=True, verbose_name='URL del Podcast')),
                ('streaming_url', models.URLField(blank=True, verbose_name='URL del Streaming')),
                ('post_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('video', 'Video'), ('highlight', 'Highlight'), ('podcast', 'Podcast'), ('streaming', 'Streaming')], default='text', max_length=20, verbose_name='Tipo de post')),
                ('category', models.CharField(blank=True, choices=[('football', 'Fútbol'), ('general_sport', 'Deporte General'), ('culture', 'Cultura'), ('music', 'Música'), ('dance', 'Danza'), ('education', 'Educación'), ('gaming', 'Gaming'), ('food', 'Comida'), ('other', 'Otro')], max_length=20, verbose_name='Categoría')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('celebrations_count', models.PositiveIntegerField(default=0, verbose_name='Celebraciones')),
                ('golazos_count', models.PositiveIntegerField(default=0, verbose_name='Golazos')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='Comentarios')),
                ('shares_count', models.PositiveIntegerField(default=0, verbose_name='Compartidos')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Visualizaciones')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Fijado')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archivado')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Permitir comentarios')),
                ('is_public', models.BooleanField(default=True, verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=500, verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, null=True, upload_to='comments/', verbose_name='Imagen')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('replies_count', models.PositiveIntegerField(default=0, verbose_name='Respuestas')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Editado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.comment', verbose_name='Comentario padre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de guardado')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='posts.post', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Post Guardado',
                'verbose_name_plural': 'Posts Guardados',
                'db_table': 'post_bookmarks',
            },
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(choices=[('like', 'Me gusta'), ('celebration', 'Celebración'), ('golazo', 'Golazo')], max_length=15, verbose_name='Tipo de reacción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reacción')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='posts.post', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reacción',
                'verbose_name_plural': 'Reacciones',
                'db_table': 'post_reactions',
            },
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Acoso'), ('hate_speech', 'Discurso de odio'), ('violence', 'Violencia'), ('inappropriate_content', 'Contenido inapropiado'), ('copyright', 'Violación de derechos de autor'), ('other', 'Otro')], max_length=30, verbose_name='Razón')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('reviewed', 'Revisado'), ('resolved', 'Resuelto'), ('dismissed', 'Desestimado')], default='pending', max_length=15, verbose_name='Estado')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('moderator_notes', models.TextField(blank=True, verbose_name='Notas del moderador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.post', verbose_name='Post')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reportador')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Reporte de Post',
                'verbose_name_plural': 'Reportes de Posts',
                'db_table': 'post_reports',
            },
        ),
        migrations.CreateModel(
            name='PostShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, max_length=200, verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de compartir')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='posts.post', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Compartir Post',
                'verbose_name_plural': 'Posts Compartidos',
                'db_table': 'post_shares',
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de visualización')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='posts.post', verbose_name='Post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Visualización de Post',
                'verbose_name_plural': 'Visualizaciones de Posts',
                'db_table': 'post_views',
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de like')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.comment', verbose_name='Comentario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Like de Comentario',
                'verbose_name_plural': 'Likes de Comentarios',
                'db_table': 'comment_likes',
                'indexes': [models.Index(fields=['comment', '-created_at'], name='comment_lik_comment_9e1199_idx'), models.Index(fields=['user', '-created_at'], name='comment_lik_user_id_219cf2_idx')],
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', '-created_at'], name='posts_user_id_dfa368_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', '-created_at'], name='posts_categor_b285e2_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type', '-created_at'], name='posts_post_ty_2afc3b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_public', '-created_at'], name='posts_is_publ_6eff95_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='comments_post_id_015fcc_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', 'created_at'], name='comments_parent__149355_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_at'], name='comments_user_id_a80af7_idx'),
        ),
        migrations.AddIndex(
            model_name='postbookmark',
            index=models.Index(fields=['user', '-created_at'], name='post_bookma_user_id_d11841_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postbookmark',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='postreaction',
            index=models.Index(fields=['post', 'reaction_type'], name='post_reacti_post_id_6674a6_idx'),
        ),
        migrations.AddIndex(
            model_name='postreaction',
            index=models.Index(fields=['user', '-created_at'], name='post_reacti_user_id_d13d8c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postreaction',
            unique_together={('user', 'post', 'reaction_type')},
        ),
        migrations.AddIndex(
            model_name='postreport',
            index=models.Index(fields=['status', '-created_at'], name='post_report_status_5f2307_idx'),
        ),
        migrations.AddIndex(
            model_name='postreport',
            index=models.Index(fields=['post', '-created_at'], name='post_report_post_id_93f6a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postreport',
            unique_together={('reporter', 'post')},
        ),
        migrations.AddIndex(
            model_name='postshare',
            index=models.Index(fields=['user', '-created_at'], name='post_shares_user_id_c3c822_idx'),
        ),
        migrations.AddIndex(
            model_name='postshare',
            index=models.Index(fields=['post', '-created_at'], name='post_shares_post_id_219864_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postshare',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['post', '-created_at'], name='post_views_post_id_cc8b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['user', '-created_at'], name='post_views_user_id_87e878_idx'),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['ip_address', '-created_at'], name='post_views_ip_addr_9baea9_idx'),
        ),
    ]
