# Generated by Django 4.2.26 on 2025-11-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_add_short_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_id',
            field=models.CharField(blank=True, max_length=8, unique=True, verbose_name='ID Corto'),
        ),
    ]
