# Generated by Django 4.2.26 on 2025-11-14 02:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('advertiser_name', models.CharField(max_length=200, verbose_name='Nombre del Anunciante')),
                ('advertiser_email', models.EmailField(max_length=254, verbose_name='Email del Anunciante')),
                ('ad_type', models.CharField(choices=[('banner', 'Banner'), ('video', 'Video'), ('sponsored_post', 'Post Patrocinado'), ('story', 'Historia')], max_length=20, verbose_name='Tipo de Anuncio')),
                ('position', models.CharField(choices=[('feed_top', 'Feed - Superior'), ('feed_middle', 'Feed - Medio'), ('feed_bottom', 'Feed - Inferior'), ('sidebar', 'Barra Lateral'), ('story', 'Historias'), ('between_posts', 'Entre Publicaciones')], max_length=20, verbose_name='Posición')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/images/', verbose_name='Imagen')),
                ('video_url', models.URLField(blank=True, verbose_name='URL del Video')),
                ('link_url', models.URLField(verbose_name='URL de Destino')),
                ('call_to_action', models.CharField(default='Ver más', max_length=50, verbose_name='Call to Action')),
                ('target_countries', models.JSONField(blank=True, default=list, verbose_name='Países Objetivo')),
                ('target_cities', models.JSONField(blank=True, default=list, verbose_name='Ciudades Objetivo')),
                ('target_age_min', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(100)], verbose_name='Edad Mínima')),
                ('target_age_max', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(100)], verbose_name='Edad Máxima')),
                ('target_interests', models.JSONField(blank=True, default=list, verbose_name='Intereses Objetivo')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Presupuesto Total')),
                ('cost_per_click', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Costo por Click (CPC)')),
                ('cost_per_impression', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Costo por Impresión (CPM)')),
                ('impressions', models.IntegerField(default=0, verbose_name='Impresiones')),
                ('clicks', models.IntegerField(default=0, verbose_name='Clicks')),
                ('conversions', models.IntegerField(default=0, verbose_name='Conversiones')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Gastado')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('paused', 'Pausado'), ('completed', 'Completado'), ('rejected', 'Rechazado')], default='draft', max_length=20, verbose_name='Estado')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de Fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Razón de Rechazo')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ads', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_clicks', to='advertising.advertisement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Click en Anuncio',
                'verbose_name_plural': 'Clicks en Anuncios',
                'ordering': ['-clicked_at'],
            },
        ),
    ]
