# Generated by Django 4.2.26 on 2025-12-02 20:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='ID de Sesión')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('position_in_feed', models.IntegerField(default=0, verbose_name='Posición en Feed')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Impresión de Anuncio',
                'verbose_name_plural': 'Impresiones de Anuncios',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='AdVideoView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('watch_duration', models.IntegerField(default=0, verbose_name='Duración vista (segundos)')),
                ('video_duration', models.IntegerField(default=0, verbose_name='Duración total (segundos)')),
                ('completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vista de Video',
                'verbose_name_plural': 'Vistas de Videos',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'Anuncio Publicitario', 'verbose_name_plural': 'Anuncios Publicitarios'},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='advertiser_logo',
            field=models.ImageField(blank=True, null=True, upload_to='ads/logos/', verbose_name='Logo del Anunciante'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='carousel_images',
            field=models.JSONField(blank=True, default=list, verbose_name='Imágenes del Carrusel'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ads', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='daily_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Presupuesto Diario (USD)'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='max_clicks',
            field=models.IntegerField(default=0, help_text='0 = sin límite', verbose_name='Máximo de Clicks Totales'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='max_impressions',
            field=models.IntegerField(default=0, help_text='0 = sin límite', verbose_name='Máximo de Impresiones Totales'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='max_impressions_per_day',
            field=models.IntegerField(default=3, help_text='Límite diario de veces que un usuario verá este anuncio', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máx. impresiones por día por usuario'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='max_impressions_per_user',
            field=models.IntegerField(default=10, help_text='Número máximo de veces que un usuario verá este anuncio', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máx. impresiones por usuario'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Baja'), (2, 'Normal'), (3, 'Alta'), (4, 'Muy Alta'), (5, 'Máxima')], default=2, help_text='Los anuncios con mayor prioridad se muestran primero', verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='show_every_n_posts',
            field=models.IntegerField(default=5, help_text='El anuncio aparecerá cada N publicaciones en el feed (ej: 5 = cada 5 posts)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Mostrar cada N publicaciones'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='show_from_hour',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Mostrar desde hora'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='show_on_weekdays',
            field=models.JSONField(blank=True, default=list, help_text='Lista de días: [0,1,2,3,4,5,6] donde 0=Lunes', verbose_name='Días de la semana'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='show_until_hour',
            field=models.IntegerField(default=23, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Mostrar hasta hora'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='target_gender',
            field=models.CharField(choices=[('all', 'Todos'), ('male', 'Masculino'), ('female', 'Femenino')], default='all', max_length=10, verbose_name='Género Objetivo'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='unique_views',
            field=models.IntegerField(default=0, verbose_name='Vistas Únicas'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='ads/videos/', verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='video_completions',
            field=models.IntegerField(default=0, verbose_name='Videos Completados'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='video_views',
            field=models.IntegerField(default=0, verbose_name='Reproducciones de Video'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='weight',
            field=models.IntegerField(default=100, help_text='Peso para rotación aleatoria (mayor peso = más probabilidad)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='adclick',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adclick',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='ad_type',
            field=models.CharField(choices=[('image', 'Imagen'), ('video', 'Video'), ('carousel', 'Carrusel'), ('banner', 'Banner'), ('sponsored_post', 'Post Patrocinado')], default='image', max_length=20, verbose_name='Tipo de Anuncio'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='advertiser_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del Anunciante'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Presupuesto Total (USD)'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='call_to_action',
            field=models.CharField(default='Ver más', max_length=50, verbose_name='Texto del Botón'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='cost_per_click',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Costo por Click (CPC)'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='cost_per_impression',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Costo por 1000 Impresiones (CPM)'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='link_url',
            field=models.URLField(blank=True, verbose_name='URL de Destino'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('feed', 'Feed Principal'), ('feed_top', 'Feed - Superior'), ('between_posts', 'Entre Publicaciones'), ('sidebar', 'Barra Lateral'), ('stories', 'Historias'), ('reels', 'Reels')], default='feed', max_length=20, verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente de Aprobación'), ('active', 'Activo'), ('paused', 'Pausado'), ('completed', 'Completado'), ('rejected', 'Rechazado')], default='draft', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título del Anuncio'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='URL del Video (YouTube/Vimeo)'),
        ),
        migrations.AddIndex(
            model_name='adclick',
            index=models.Index(fields=['ad', '-clicked_at'], name='advertising_ad_id_39e20c_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['status', 'is_active', 'start_date', 'end_date'], name='advertising_status_3ec1ee_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['position', 'status'], name='advertising_positio_b79dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['priority', '-created_at'], name='advertising_priorit_3a5101_idx'),
        ),
        migrations.AddField(
            model_name='advideoview',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_views_log', to='advertising.advertisement'),
        ),
        migrations.AddField(
            model_name='advideoview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adimpression',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_impressions', to='advertising.advertisement'),
        ),
        migrations.AddField(
            model_name='adimpression',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adclick',
            name='impression',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertising.adimpression'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['ad', 'user', '-viewed_at'], name='advertising_ad_id_9d2a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['user', '-viewed_at'], name='advertising_user_id_87c4a5_idx'),
        ),
    ]
