# Generated by Django 4.2.16 on 2025-12-21 00:07

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la cuenta')),
                ('account_type', models.CharField(choices=[('bank', 'Cuenta Bancaria'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('mercadopago', 'MercadoPago')], max_length=20, verbose_name='Tipo de cuenta')),
                ('account_number', models.CharField(max_length=100, verbose_name='Número de cuenta/Teléfono')),
                ('account_holder', models.CharField(max_length=200, verbose_name='Titular de la cuenta')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del banco')),
                ('currency', models.CharField(choices=[('COP', 'Peso Colombiano'), ('USD', 'Dólar Estadounidense')], default='COP', max_length=3, verbose_name='Moneda')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Cuenta principal')),
                ('for_classifieds', models.BooleanField(default=True, verbose_name='Para clasificados')),
                ('for_advertising', models.BooleanField(default=True, verbose_name='Para publicidad')),
                ('for_donations', models.BooleanField(default=True, verbose_name='Para donaciones')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuenta de Pago',
                'verbose_name_plural': 'Cuentas de Pago',
                'db_table': 'payment_accounts',
                'ordering': ['-is_primary', '-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donation_fee_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Comisión de donaciones (%)')),
                ('default_currency', models.CharField(default='COP', max_length=3, verbose_name='Moneda por defecto')),
                ('auto_approve_under', models.DecimalField(decimal_places=2, default=0, help_text='0 = requiere verificación manual siempre', max_digits=12, verbose_name='Auto-aprobar pagos menores a')),
                ('notify_admin_on_payment', models.BooleanField(default=True, verbose_name='Notificar admin en pagos')),
                ('admin_notification_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de notificaciones')),
                ('payment_instructions', models.TextField(blank=True, verbose_name='Instrucciones de pago')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='Términos y condiciones')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Plataforma',
                'verbose_name_plural': 'Configuración de Plataforma',
                'db_table': 'platform_settings',
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del plan')),
                ('service_type', models.CharField(choices=[('classified_basic', 'Clasificado Básico'), ('classified_featured', 'Clasificado Destacado'), ('classified_premium', 'Clasificado Premium'), ('ad_banner', 'Banner Publicitario'), ('ad_sponsored_post', 'Post Patrocinado'), ('ad_story', 'Historia Patrocinada'), ('enterprise_verified', 'Verificación de Empresa')], max_length=30, unique=True, verbose_name='Tipo de servicio')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio')),
                ('currency', models.CharField(default='COP', max_length=3, verbose_name='Moneda')),
                ('duration_value', models.PositiveIntegerField(default=30, verbose_name='Duración')),
                ('duration_unit', models.CharField(choices=[('days', 'Días'), ('weeks', 'Semanas'), ('months', 'Meses')], default='days', max_length=10, verbose_name='Unidad de duración')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='Características incluidas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan de Precios',
                'verbose_name_plural': 'Planes de Precios',
                'db_table': 'pricing_plans',
                'ordering': ['service_type', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(max_length=50, unique=True, verbose_name='Código de referencia')),
                ('transaction_type', models.CharField(choices=[('classified_payment', 'Pago de Clasificado'), ('advertising_payment', 'Pago de Publicidad'), ('donation', 'Donación'), ('subscription', 'Suscripción'), ('refund', 'Reembolso')], max_length=30, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('pending_verification', 'Pendiente de Verificación'), ('processing', 'Procesando'), ('completed', 'Completada'), ('failed', 'Fallida'), ('refunded', 'Reembolsada'), ('cancelled', 'Cancelada')], default='pending', max_length=25, verbose_name='Estado')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('currency', models.CharField(default='COP', max_length=3, verbose_name='Moneda')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Transferencia Bancaria'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('credit_card', 'Tarjeta de Crédito'), ('paypal', 'PayPal'), ('mercadopago', 'MercadoPago')], max_length=20, verbose_name='Método de pago')),
                ('content_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de contenido')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='ID del objeto')),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='Comprobante de pago')),
                ('payment_proof_url', models.URLField(blank=True, verbose_name='URL del comprobante')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Notas de verificación')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='enterprises.enterprise', verbose_name='Empresa')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentaccount', verbose_name='Cuenta de destino')),
                ('pricing_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.pricingplan', verbose_name='Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseClassifiedPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classified_id', models.CharField(blank=True, max_length=50, verbose_name='ID del clasificado')),
                ('classified_type', models.CharField(blank=True, max_length=30, verbose_name='Tipo de clasificado')),
                ('status', models.CharField(choices=[('pending_payment', 'Pendiente de Pago'), ('pending_verification', 'Pendiente de Verificación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('expired', 'Expirado')], default='pending_payment', max_length=25, verbose_name='Estado')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('classified_data', models.JSONField(blank=True, default=dict, verbose_name='Datos del clasificado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classified_payments', to='enterprises.enterprise', verbose_name='Empresa')),
                ('pricing_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.pricingplan', verbose_name='Plan')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classified_payment', to='payments.transaction', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Pago de Clasificado Empresarial',
                'verbose_name_plural': 'Pagos de Clasificados Empresariales',
                'db_table': 'enterprise_classified_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del donante')),
                ('donor_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del donante')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Donación anónima')),
                ('campaign_id', models.CharField(blank=True, max_length=50, verbose_name='ID de campaña')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('currency', models.CharField(default='COP', max_length=3, verbose_name='Moneda')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje de apoyo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('pending_verification', 'Pendiente de Verificación'), ('completed', 'Completada'), ('failed', 'Fallida')], default='pending', max_length=25, verbose_name='Estado')),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Comisión plataforma')),
                ('athlete_receives', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Atleta recibe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_donations_received', to=settings.AUTH_USER_MODEL, verbose_name='Atleta')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_donations_made', to=settings.AUTH_USER_MODEL, verbose_name='Donante')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation', to='payments.transaction', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'db_table': 'donation_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisingPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ad_title', models.CharField(max_length=200, verbose_name='Título del anuncio')),
                ('ad_content', models.TextField(verbose_name='Contenido')),
                ('ad_image', models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='Imagen')),
                ('ad_url', models.URLField(blank=True, verbose_name='URL de destino')),
                ('status', models.CharField(choices=[('pending_payment', 'Pendiente de Pago'), ('pending_verification', 'Pendiente de Verificación'), ('approved', 'Aprobado'), ('active', 'Activo'), ('paused', 'Pausado'), ('completed', 'Completado'), ('rejected', 'Rechazado')], default='pending_payment', max_length=25, verbose_name='Estado')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='Impresiones')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Clics')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertising_payments', to='enterprises.enterprise', verbose_name='Empresa')),
                ('pricing_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.pricingplan', verbose_name='Plan')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertising_payment', to='payments.transaction', verbose_name='Transacción')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertising_payments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pago de Publicidad',
                'verbose_name_plural': 'Pagos de Publicidad',
                'db_table': 'advertising_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='transaction_user_id_ced08a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', '-created_at'], name='transaction_status_b84006_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='transaction_transac_a32e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_code'], name='transaction_referen_0764c1_idx'),
        ),
    ]
