# Generated by Django 4.2.16 on 2025-12-20 14:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SportCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icono')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Deporte',
                'verbose_name_plural': 'Categorías de Deportes',
                'db_table': 'donation_sport_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('age', models.PositiveIntegerField(verbose_name='Edad')),
                ('height', models.CharField(max_length=20, verbose_name='Altura')),
                ('weight', models.CharField(blank=True, max_length=20, verbose_name='Peso')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('country', models.CharField(default='Colombia', max_length=100, verbose_name='País')),
                ('position', models.CharField(max_length=100, verbose_name='Posición/Especialidad')),
                ('team', models.CharField(blank=True, max_length=200, verbose_name='Equipo/Club')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Años de experiencia')),
                ('achievements', models.TextField(blank=True, verbose_name='Logros deportivos')),
                ('description', models.TextField(verbose_name='Descripción/Historia')),
                ('goal_description', models.TextField(verbose_name='¿Para qué necesitas el apoyo?')),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Meta de recaudación (COP)')),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto recaudado (COP)')),
                ('donors_count', models.PositiveIntegerField(default=0, verbose_name='Número de donantes')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de aprobación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('suspended', 'Suspendido')], default='pending', max_length=20, verbose_name='Estado')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='donations.sportcategory', verbose_name='Deporte')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Deportista',
                'verbose_name_plural': 'Perfiles de Deportistas',
                'db_table': 'donation_athlete_profiles',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AthleteMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video')], max_length=10, verbose_name='Tipo de medio')),
                ('file', models.FileField(upload_to='donations/athletes/%Y/%m/', verbose_name='Archivo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='donations/thumbnails/%Y/%m/', verbose_name='Miniatura')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Es portada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='donations.athleteprofile', verbose_name='Deportista')),
            ],
            options={
                'verbose_name': 'Medio del Deportista',
                'verbose_name_plural': 'Medios de Deportistas',
                'db_table': 'donation_athlete_media',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del donante')),
                ('donor_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del donante')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Donación anónima')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Monto (COP)')),
                ('payment_method', models.CharField(choices=[('card', 'Tarjeta de Crédito/Débito'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('pse', 'PSE'), ('cash', 'Efectivo'), ('other', 'Otro')], max_length=20, verbose_name='Método de pago')),
                ('transaction_id', models.CharField(blank=True, max_length=200, verbose_name='ID de transacción')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completada'), ('failed', 'Fallida'), ('refunded', 'Reembolsada')], default='pending', max_length=20, verbose_name='Estado')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje de apoyo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de donación')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.athleteprofile', verbose_name='Deportista')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_made', to=settings.AUTH_USER_MODEL, verbose_name='Donante')),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'db_table': 'donations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['athlete', 'status', '-created_at'], name='donations_athlete_cd5ec8_idx'), models.Index(fields=['donor', '-created_at'], name='donations_donor_i_1842e7_idx'), models.Index(fields=['status', '-created_at'], name='donations_status_80555b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='athleteprofile',
            index=models.Index(fields=['status', '-created_at'], name='donation_at_status_b2273d_idx'),
        ),
        migrations.AddIndex(
            model_name='athleteprofile',
            index=models.Index(fields=['sport', 'status'], name='donation_at_sport_i_5199b0_idx'),
        ),
        migrations.AddIndex(
            model_name='athleteprofile',
            index=models.Index(fields=['is_featured', '-created_at'], name='donation_at_is_feat_ed7825_idx'),
        ),
    ]
